const StringConstants = {
    SUBMIT: "Submit",
    CANCEL: "Cancel",
    OK: "Ok",
    DELETE: "Delete",
    CONTINUE: "Continue",
    WARNING: "Warning",
    CONFIRM: "Confirm",
    SELECT_TERM: "Select Term",
    SELECT_PROGRAM: "Select Program",
    SELECT_COMMITTEE: "Select Committee",
    ERROR: "Something went wrong.",
    EXCEL: "Excel",
    COPY: "Copy",
    BACK: "Back",
    CONFIRM_DELETE: "Confirm Delete",
    REMOVE_WARNING: "Are you sure you want to remove this person from the mailing list?",
    ADD_MEMBER: "Add New Member",
    RETIRE_MEMBER: "Retire Member",
    SUCCESS: "Success",
    RETIREMENT_PROCESS: "Retirement Process",
    LIST_MEETING: "List Meeting",
    COMMITTEE_ASSIGNMENT:"Committees Assignment",
};

export default StringConstants;